site_name: DASC Lab Starter Project
site_description: Student guide and exercises for the DASC lab starter project
repo_url: https://github.com/MarshallVielmetti/dasc_lab_starter_project
repo_name: MarshallVielmetti/dasc_lab_starter_project
edit_uri: ""

theme:
  name: material
  features:
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Dynamics Models: dynamics-models.md
      # - Overview: dynamics-models.md
      # - Linear System: dynamics_models/linear_system.md
      # - Single Integrator: dynamics_models/single_integrator.md
      # - Double Integrator: dynamics_models/double_integrator.md
  - Background: background.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - _startergen/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js
